#!/bin/bash

# case-menu: a menu driven system information program

clear
echo "
Please Select:

1. Display System Information
2. Display Disk Space
3. Display Home Space Utilization
0. Quit
"

read -p "Enter selection [0-3] > "

case "$REPLY" in 
0)   echo "Program terminated."
     exit
     ;;
1)   echo "Hostname: $HOSTNAME"
     uptime
     ;;
2)   df -h
     ;;
3)   if [[ "$(id -u)" -eq o ]]; then
     echo "Home Space Utilization (All users)"
     du -sh /home/*
     else
     echo "Home Space Utilization ($USER)"
     du -sh "$HOME"
     fi
     ;;
*)   echo "Invalid entry" >&2
     exit 1
     ;;
esac
report_home_space () {
	local format="%8s%10s%10s\n"
	local i dir_list total_files total_dirs total_size user_name

	if [[ "$(id -u)" -eq o ]]; then
		dir_list=/home/*
		user_name="All Users"
	else
		dir_list="$HOME"
		user_name="$USER"
	fi

	echo "<h2>Home Space Utilization ($user_name)</h2>"

	for i in $dir_list; do

		total_files="$(find "$i" -type f | wc -l)"
		total_dirs="$(find "$i" -type d | wc -l)"
		total_size="$(du -sh '$i" | cut -f 1)"

		echo "<h3>$i</h3>"
		echo "<pre>"
		printf "$format" "Dirs" "Files" "Size"
		printf "$format" "----" "----" "----"
		printf "$format" "$total_dirs" "total_files" "$total_size"
		echo "</pre>"
	done
	return
}
